name: Services - Build, Lint and Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: choice
        options:
          - "dev"
          - "production"

      service:
        description: Service
        required: true
        type: choice
        options:
          - "all"
          - "service1"
          - "service2"

  pull_request:
    branches: [dev, main]
    paths:
      - "services/**"

jobs:
  build-turbo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Lint services
        run: npm run lint

      - name: Build
        run: npm run build
